name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # 1. Production環境を指定する
    environment: Production
    
    # 2. varsコンテキストを使ってTIMEOUT変数を参照する
    timeout-minutes: ${{ vars.TIMEOUT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run deployment script
        run: |
          echo "Starting deployment to Production..."
          # ここにデプロイ処理を記述
          echo "Deployment finished."