name: example
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # ← 環境「Production」に紐づく変数を参照
    environment: Production      

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 長時間走るステップ
        # vars.TIMEOUT は文字列なので fromJSON で整数に変換
        timeout-minutes: ${{ fromJSON(vars.TIMEOUT) }}
        run: |
          echo "Doing long task..."
          sleep 300
          echo "Done long task!"
