name: Two‑Job Dynamic Timeout
on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: Production
    outputs:
      timeout_value: ${{ steps.set-timeout.outputs.value }}
    steps:
      - id: set-timeout
        run: echo "value=${{ vars.TIMEOUT || '60' }}" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: ${{ fromJSON(needs.setup.outputs.timeout_value) }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "ジョブは ${{ needs.setup.outputs.timeout_value }} 分でタイムアウトします"
          sleep 300
