# .github/workflows/dynamic-timeout.yml
# ------------------------------------
# Production 環境に「TIMEOUT」変数（数値のみ）を登録しておくと、
# その値がジョブ全体の timeout‑minutes に反映されます。
# TIMEOUT が未設定なら 60 分をデフォルトにします。

name: Dynamic Timeout (single job)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production          # ここで環境変数をバインド

    # Production 環境の vars.TIMEOUT を env.TIMEOUT に流し込み
    # 空なら '60' をフォールバック
    env:
      TIMEOUT: ${{ vars.TIMEOUT || '60' }}

    # ジョブ全体のタイムアウトを動的に設定
    timeout-minutes: ${{ fromJSON(env.TIMEOUT) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show timeout value
        run: echo "TIMEOUT is set to ${{ env.TIMEOUT }} minutes"

      - name: Long task
        run: |
          echo "Starting long task..."
          sleep 300
          echo "Done long task!"
