name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    # ⬇️ ここを修正: TIMEOUT変数が空、または存在しない場合、デフォルトで30分に設定
    timeout-minutes: ${{ vars.TIMEOUT || 30 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (オプション) デバッグ用に変数の値を出力するステップ
      - name: Debug Timeout Variable
        run: echo "The timeout value is '${{ vars.TIMEOUT }}'. The final timeout is ${{ vars.TIMEOUT || 30 }} minutes."

      - name: Run deployment script
        run: |
          echo "Starting deployment to Production..."
          # ...デプロイ処理...
          echo "Deployment finished."